### ISSUE TITLE
Error about Terminal and Notebook kernels

### ISSUE THREAD

**Issue by uysalserkan** [aws/studio-lab-examples#15]
**Describe the bug**
About python package installation error. When I install a package on terminal with `pip` command, I cannot reach that package on notebook.

**To Reproduce**
1. Open a notebook and a terminal.
2. Go to terminal and install a package with `pip` or `pip3`.
3. Switch tab and try to import that installed package. 

**Expected behavior**
Success import installed package which are installed on terminal.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser Chrome
 - Version Version 96.0.4664.45 (Official Build) (64-bit)

**Others**
Temp. solutions is install all packages with notebook commands like `!pip3 install spacy`.

**Comment by EmilyWebber** [comment]
Hi - per our FAQ's you can install into the kernel using the `%` sign, rather than the `!`.

https://studiolab.sagemaker.aws/faq

Alternatively, you can define a conda environment via yml, then build this with your terminal, and select it as the kernel when you open your notebook. I've tested spacy installs with `%pip install spacy` and `import spacy`, both of which work on my end.
