### ISSUE TITLE
we are experiencing elevated fault rate in start runtime API. The SageMaker Studio Lab team is working to restore the service.

### ISSUE THREAD

**Issue by saleemmalik10835** [aws/studio-lab-examples#155]
its been more than 3 days and im still getting this issue, i cant run cpu or even gpu runtimes in sagemaker
how long is this going to even take man

**Comment by aozorahime** [comment]
up

**Comment by saleemmalik10835** [comment]
Ah finally

**Comment by aozorahime** [comment]
btw, I can run the CPU but not GPU today

**Comment by icoxfog417** [comment]
@saleemmalik10835 Sorry for the long inconvenience of Studio Lab. As you know, the service was back and we confirmed that we can say it to you. I will close this issue because the mentioned problem is solved.

But as @aozorahime said, the GPU instance is sometime unavailable because of another instance allocation issue. Of course, we deal with this problem now.
