### ISSUE TITLE
I can not now to create new conda environments: get error SpecNotFound: Invalid name, try the format: user/package

### ISSUE THREAD

**Issue by Sandy4321** [aws/studio-lab-examples#211]
**Describe the bug**

after attempt to update conda version (as was recomended to ver 24)
I can not now to create new conda environments: get error SpecNotFound: Invalid name, try the format: user/package

-----------------
(studiolab) studio-lab-user@default:~$ conda env create --name apr17_sander  python=3.9

SpecNotFound: Invalid name, try the format: user/package

(studiolab) studio-lab-user@default:~$ conda activate default
(default) studio-lab-user@default:~$ conda env create --name apr17_sander  python=3.9

SpecNotFound: Invalid name, try the format: user/package

(default) studio-lab-user@default:~$ conda env create --name apr17_my_env python=3.9

SpecNotFound: Invalid name, try the format: user/package

(default) studio-lab-user@default:~$ conda activate apr16_sander_environment  
(apr16_sander_environment) studio-lab-user@default:~$ conda deactivate
(default) studio-lab-user@default:~$ conda deactivate
(studiolab) studio-lab-user@default:~$ conda deactivate
studio-lab-user@default:~$ conda env create --name apr17_sander  python=3.9

SpecNotFound: Invalid name, try the format: user/package

studio-lab-user@default:~$ 
-----------------
 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 
Version 111.0.5563.148 (Official Build) (64-bit)

**Additional context**

**Comment by Sandy4321** [comment]
fresh example 
studio-lab-user@default:~$ conda activate apr16_sander_environment
(apr16_sander_environment) studio-lab-user@default:~$ conda activate base
(base) studio-lab-user@default:~$ conda env create --name apr17_my_env python=3.9

SpecNotFound: Invalid name, try the format: user/package

(base) studio-lab-user@default:~$

**Comment by icoxfog417** [comment]
Hello @Sandy4321 , thank you for choosing Studio Lab for your experiment. We are sorry to hear that you encountered an error. It looks like this error is related to `conda` rather than Studio Lab. You may find some useful solutions in the following issue or Stack Overflow. 

https://github.com/conda/conda/issues/3859

We hope this helps you and wish you all the best with your experiment.

**Comment by Sandy4321** [comment]
also you did not mentioned what  is written above 
after attempt to update conda version (as was recomended to ver 24)
I can not now to create new conda environments: get error SpecNotFound: Invalid name, try the format: user/package
MEANING IN BEGINING ALL WORKED PERFECTLY 
then at least can you restart my all profile 
then I will not update conda , since conda update is broken for year in your design
and hopefully all will work again

**Comment by Sandy4321** [comment]
seems to be conda got broken when I tried to updated it to new version - how to initialize my profile to get initial version ?

**Comment by icoxfog417** [comment]
To initialize the Studio Lab environment, deleting the account and creating the account again is the most simple way. Before taking this action, I recommend you to confirm the `conda --version` command returns response or not. If it returns the version number, the `conda` itself is working fine. The error `SpecNotFound` does not mean the breaking of `conda` itself but the usage of the conda command will have some troubles. If you have the further question about the conda, ask the questions in Q&A site for conda community will be a good remedy.

**Comment by MicheleMonclova** [comment]
the account will be restored. You will not have to go through an approval.
But please make sure you save what you want to save before you delete your
account.

**Comment by Sandy4321** [comment]
ok then how to delete account 
and how to create account ?

**Comment by icoxfog417** [comment]
Please refer the `Delete your account` section. The account creation process is as same as the way you have created the account.

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab-manage-account.html

We recommend you to save what you want to save before you delete your account as Michele said. At the same time, I recommend you to confirm the `conda --version` command returns response or not. Because if it returns the version number, the conda itself is working fine. Please make sure you need to initialize the environment or not.

**Comment by Sandy4321** [comment]
I still have the same bug
pls clarify is there way to create new environment or not?
![image](https://github.com/aws/studio-lab-examples/assets/11426119/01152793-7cbf-4839-bfe5-7624ccbaa9ec)

**Comment by icoxfog417** [comment]
This is not Studio Lab bug, caused by wrong command usage. Please refer [[Creating an environment with commands](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id1)](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands)
