### ISSUE TITLE
not working in terminal :  conda install matplotlib

### ISSUE THREAD

**Issue by Sandy4321** [aws/studio-lab-examples#212]
**Describe the bug**

**To Reproduce**
I try to install matplotlib by usual way - use command line from terminal 
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda install matplotlib

![image](https://user-images.githubusercontent.com/11426119/233734086-0299b54a-82b3-4599-a611-2a9435d614f7.png)

then conda list confirms that matplotlib is installed 
![image](https://user-images.githubusercontent.com/11426119/233734368-ebf07004-829e-45f4-9c9f-397efe46d8c8.png)

(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda list matplotlib
# packages in environment at /home/studio-lab-user/.conda/envs/studiolab:
#
# Name                    Version                   Build  Channel
matplotlib                3.7.1            py39hf3d152e_0    conda-forge
matplotlib-base           3.7.1            py39he190548_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge

but when I try to use matplotlib from notebook - it written it is not installed 
![image](https://user-images.githubusercontent.com/11426119/233734509-b2174e53-d162-49bb-953b-82db21b01670.png)

 closing current notebook and open new one is not helping

**Expected behavior**
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda install matplotlib

should provide capability to use matplotlib from notebook

Notice I do have only one base environment
![image](https://user-images.githubusercontent.com/11426119/233734845-8a0e8c59-87d0-470c-8253-4d0d31044a9a.png)

and 
![image](https://user-images.githubusercontent.com/11426119/233735028-0b93e52c-dbaf-4a7a-bde4-c1d844ada2ff.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 11
 - Browser [e.g. chrome, safari] edge

**Comment by npmajisha** [comment]
Based on your screenshots, it seems like you are installing matplotlib in the `studiolab` environment.

This environment should only be used for installing jupyterlab and jupyter server extensions. The environment used for notebook kernels is `default`, which you can see from the kernel dropdown `default:Python`. 

There are two ways you can fix this problem:

1. In order to install packages into the `default` environment, you will have to activate the `default` environment so that they are available in your notebooks - `conda activate default`.  After switching the environment, you can continue to install the packages you want.

2. Alternatively, the recommended way for installation as described [here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab-use-manage.html#studio-lab-use-manage-conda) is to use `%conda install <package>` or `%pip install <package>` in a notebook cell which will ensure that the packages are installed in the correct conda environment without having to remember to activate it.


Hope this helps.

**Comment by Sandy4321** [comment]
In order to install packages into the default environment, you will have to activate the default environment so that they are available in your notebooks - conda activate default

but as you can see from above 
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda install matplotlib
active environment is studiolab
do you mean studiolab is not default environment?

**Comment by icoxfog417** [comment]
`default` and `studiolab` is the different environment.

**Comment by Sandy4321** [comment]
I see, let me try

**Comment by MicheleMonclova** [comment]
can we close this issue?

**Comment by Sandy4321** [comment]
no closing pls, it is still bug

**Comment by icoxfog417** [comment]
We discuss the `default` and `studiolab` confusion at #218 and close this issue because installing matplotlib is possible in Studio Lab.
