### ISSUE TITLE
No evironment write permissions on Free SageMaker Studio Lab Account

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [aws/studio-lab-examples#220]
![Screenshot from 2023-06-21 14-11-43](https://github.com/aws/studio-lab-examples/assets/51626734/6a1760e4-7fbc-4d88-9dd2-2aa016b1f356)
![Screenshot from 2023-06-21 14-11-12](https://github.com/aws/studio-lab-examples/assets/51626734/ae0f6d92-596d-4613-8ec5-910f7f05d0d1)

**Comment by MicheleMonclova** [comment]
Hi Arlsan, this is known issue.  You need SUDO access to update your conda environment.  We are working on upgrading the Conda version.

**Comment by Arslan-Mehmood1** [comment]
in colab we don't face such issues when installing and upgrading libraries. We can almost run any project in google colab. but aws seems more professional to me, that's why I wanna use aws. Even I couldn't run simple keras transfer learning project on aws free sagemaker studio lab due to same issues. Please provide any solution

**Comment by icoxfog417** [comment]
@Arslan-Mehmood1 could you please tell us what kinds of packages did you install? Basically, the write permission to `opt/conda` is not required.

**Comment by icoxfog417** [comment]
We are marking this issue as closed since I believe the new [SageMaker distribution environment](https://aws.amazon.com/jp/blogs/machine-learning/get-started-with-the-open-source-amazon-sagemaker-distribution/) is working well for you now. Please let me know if you have any other questions or concerns.
