### ISSUE TITLE
Can't configure profile with AWS CLI for using AWS Built-in sagemaker algorithms 

### ISSUE THREAD

**Issue by DL-stack** [aws/studio-lab-examples#30]
Hi everybody,

I am trying to use AWS built-in algorithms in Sagemaker Studio Lab. For that I need an execution role and region etc. 
When I try to run my code it outputs

ValueError: Must setup local AWS configuration with a region supported by SageMaker.

Is it even possible to link access AWS resources in Studiolab?

Many thanks in advance!

**Comment by EmilyWebber** [comment]
Hi! The use case you are describing is exactly why we have this example notebook:
- https://github.com/aws/studio-lab-examples/blob/main/connect-to-aws/Access_AWS_from_Studio_Lab.ipynb 

Your net net is:
1/ Ensure you have proper training and authorization to use your AWS access and secret keys. If you are an AWS account admin, you can find this in your IAM console. If you are not, work with your admin to determine if this pattern is appropriate for you. 

2/ If you are qualified to manage your AWS keys, create a new file called `~/.aws/credentials`. There, copy and paste in your access and secret keys.

3/ Remove any cells you ran in a notebook to create or verify those files.

4/ Create a SageMaker execution role. The easiest way to do this is via the console - you can create a new SageMaker execution role when create a notebook instance or a Studio user profile. Once this is done, paste in the arn (Amazon Resource Name), for this execution role.

5/ Go forth and scale up on SageMaker! After that,  once you are using the SageMaker Python SDK, you should be able to use all code-based features within SageMaker, such as training, hosting, tuning, autopilot, pipelines, etc.

**Comment by derekschan** [comment]
Hi @EmilyWebber. Can you share an example that doesn't require AWS account information and avoids "ValueError: Must setup local AWS configuration with a region supported by SageMaker"? 

Since the SageMaker Studio Lab website emphasizes no costs and no need to sign up for an AWS account, a team and I are exploring whether to onboard students to try AWS SageMaker Studio Lab. So far we find the same code that runs in SageMaker Studio in an AWS account doesn't run on SageMaker Studio **Lab** outside an AWS account. Thank you in advance.

**Comment by EmilyWebber** [comment]
Hi @derekschan - thanks for the comment. This is actually expected behavior right now - Studio Lab defaults to not having access to any AWS API's unless explicitly granted. To date, that is solved only by the pattern mentioned above in this issue, explicitly installing AWS key permissions to utilize them. 

Should that ever change in the future we will be sure to let you know! I'll mark your comment as a feature enhancement.

**Comment by derekschan** [comment]
Thank you, @EmilyWebber.
