### ISSUE TITLE
Install htop via "sudo apt install htop"

### ISSUE THREAD

**Issue by Chertushkin** [aws/studio-lab-examples#31]
**Is your feature request related to a problem? Please describe.**
Actually, no, there is not problem. Everything works, but it would be nice to have it.

**Describe the solution you'd like**
I would like to be able to install `htop` on my machine from Sagemaker Studio Lab. When I do it, I got permission denied.

**Describe alternatives you've considered**
I work around this issue by doing `conda install htop`. And it worked. But it would be cool to be able to install via `sudo apt install htop`, as it is very likely I will need to install some other packages in the future. Is it possible?

**Additional context**
No additional context. Just thank you very much for this initiative, it is very cool!

**Comment by EmilyWebber** [comment]
Hi! Glad you're enjoying the free compute :). I am curious - would the `sudo apt install htop` provide anything that `conda install htop` does not? Said another way, what is it about the `sudo apt install htop` that provides functionality unmet by `conda install htop`? At this point in time we don't support `sudo` commands, largely because most of the DS/ML functionality can be met by `conda` and `pip` installs.

**Comment by Chertushkin** [comment]
Hm. Actually the `conda install htop` is a perfect solution in this circumstance. So I guess it's fine to close this thread. Thank you very much!
