### ISSUE TITLE
You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms

### ISSUE THREAD

**Issue by hibxhhihey** [aws/studio-lab-examples#90]
**Describe the bug**
When I started the project: You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms.
**To Reproduce**
1、Go to ''Login page and sign in"
2、Click on 'Start Runtime'
3、See error

**Expected behavior**
COU/GPU runtime should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/89524271/158744651-a56f4549-97ec-4ae6-9e6d-1766ddae058d.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Google Chrome

**Comment by Ben-Yee** [comment]
I got the same issue...so confused.The same thing happened to my schoolmate.

**Comment by hibxhhihey** [comment]
I want to know where are you from...





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月17日(星期四) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)





 
我遇到了同样的问题...太困惑了。同样的事情也发生在我的同学身上。
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by hibxhhihey** [comment]
Definitely not. I tried to log in using a VPN in another region, but couldn't open the web page

**Comment by MicheleMonclova** [comment]
Hi all. Thank you for your patience.  We have been experiencing a large surge in request for GPU. We are currently working on this, but in the meantime please continue with CPU.

**Comment by hibxhhihey** [comment]
However, the customer service staff told me that if I continued to use it, my account would be blocked again. I dare not use it now. Can I still use it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 上午8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)





 
Hi all. Thank you for your patience.  We have been experiencing a large surge in request for GPU. We are currently working on this, but in the meantime please continue with CPU.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MicheleMonclova** [comment]
Thank you all for communicating here. Yesterday we noticed some accounts making excessive GPU requests, and we had to block them. We will be managing this more gracefully in the future, and will be updating our FAQs to make it more clear that this is an unacceptable use of our service.
We are still in preview, so we appreciate your patience and your responsible usage.
We are looking into reinstating these accounts.
Michele Monclova
SageMaker Studio Lab Service Team

**Comment by Ben-Yee** [comment]
Thanks for your reply.I am so worried about my unfinished code on SageMaker Studio Lab and looking forward to reinstating my account as soon as possible.And i totally understand what SageMaker Studio Lab provides is open and free compute resources for those who try to get start with AI. Maybe you can define the unacceptable use of service more specific in numbers so we can use GPU more properly.
Again,thanks for your reply sincerely!



在 2022-03-18 12:27:47，"MicheleMonclova" ***@***.***> 写道：

Thank you all for communicating here. Yesterday we noticed some accounts making excessive GPU requests, and we had to block them. We will be managing this more gracefully in the future, and will be updating our FAQs to make it more clear that this is an unacceptable use of our service.
We are still in preview, so we appreciate your patience and your responsible usage.
We are looking into reinstating these accounts.
Michele Monclova
SageMaker Studio Lab Service Team

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ben-Yee** [comment]
嘿，我想问下工作人员恢复你的帐号了吗？可以用CPU打开项目打开项目吗？(Hey,I want to ask if the staff restore your accout now?Can you use at least CPU runtime to open the project right now?)



在 2022-03-17 20:15:58，"hibxhhihey" ***@***.***> 写道：

I want to know where are you from...





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2022年3月17日(星期四) 晚上8:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)






我遇到了同样的问题...太困惑了。同样的事情也发生在我的同学身上。

-
直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hibxhhihey** [comment]
我不知道，我一直没有使用，我怕再次给我禁了，就什么东西都弄不出来了。我还在等。你呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aws/studio-lab-examples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)





 嘿，我想问下工作人员恢复你的帐号了吗？可以用CPU打开项目打开项目吗？(Hey,I want to ask if the staff restore your accout now?Can you use at least CPU runtime to open the project right now?)
 
 
 
 在 2022-03-17 20:15:58，"hibxhhihey" ***@***.***&gt; 写道：
 
 I want to know where are you from...
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: ***@***.***&amp;gt;;
 发送时间: 2022年3月17日(星期四) 晚上8:14
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
 主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)
 
 
 
 
 
 
 我遇到了同样的问题...太困惑了。同样的事情也发生在我的同学身上。
 
 -
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
 使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
 您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&gt;  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ben-Yee** [comment]
我点了，还是像图片那样，没法请求runtime，不管是CPU还是GPU



在 2022-03-18 14:29:23，"hibxhhihey" ***@***.***> 写道：

我不知道，我一直没有使用，我怕再次给我禁了，就什么东西都弄不出来了。我还在等。你呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aws/studio-lab-examples" ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)





嘿，我想问下工作人员恢复你的帐号了吗？可以用CPU打开项目打开项目吗？(Hey,I want to ask if the staff restore your accout now?Can you use at least CPU runtime to open the project right now?)



在 2022-03-17 20:15:58，"hibxhhihey" ***@***.***&gt; 写道：

I want to know where are you from...





------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: ***@***.***&amp;gt;;
发送时间: 2022年3月17日(星期四) 晚上8:14
收件人: ***@***.***&amp;gt;;
抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;
主题: Re: [aws/studio-lab-examples] You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms (Issue #90)






我遇到了同样的问题...太困惑了。同样的事情也发生在我的同学身上。

-
直接回复此电子邮件，在 GitHub 上查看或取消订阅。
使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地对通知进行分类。
您收到此邮件是因为您创作了该线程。Message ID: ***@***.***&amp;gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***&gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chalili12** [comment]
> 

好像都没有，等恢复以后把代码取出来去别处做吧，旷视和百度都有免费算力，就是用不了pytorch（悲

**Comment by icoxfog417** [comment]
@hibxhhihey do you sill have the problem? If you still have the problem despite you do not violate the service term, please let us know.

**Comment by icoxfog417** [comment]
I will close this issue. Please feel free to raise a new issue if you still have the trouble.
