### ISSUE TITLE
No runtime available

### ISSUE THREAD

**Issue by onaly** [aws/studio-lab-examples#96]
Hello,

First of all thanks for providing this amazing service.
I just want to point out that there seems to be a problem for some time now.
We can't start a session with GPU anymore without getting the message "There is no runtime available right now. Please change the compute type or try again later."
I can understand that the service being free, it can't be unlimited but it should be transparent.
Normally it should be possible to know how many runtimes are available before even starting. Or maybe there should be a queue system so that everybody can have access to a GPU runtime.

Thanks a lot for your help.

![bugslab](https://user-images.githubusercontent.com/66476206/160179867-0d38a977-4ee4-4c96-a6e1-e978ad1ef09f.PNG)

**Comment by lorazabora** [comment]
Don’t worry, everyone without an exception has this error and we’re still waiting for them to fix it, also a note regarding your queue idea i don’t agree with it and i think it doesn’t make much sense since the service is request only in the meantime and that’s all to ensure that there wouldn’t be such an interruption to begin with, to prove what I’m saying that’s how it always was since it started

I believe that there may be some other reasoning for this bug such as them increasing the capacity or something just about time and hopefully they fix it

**Comment by MicheleMonclova** [comment]
Hi, thank you for your patience.  It is true there has been a surge of GPU demand.  While we address this issue please continue with CPU, which is also pretty powerful.

**Comment by icoxfog417** [comment]
@onaly Thank you for your confirmation and 👍 on #88!
